/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "nyct-subway.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TripReplacementPeriod, TripReplacementPeriod, AUTO)


PB_BIND(NyctFeedHeader, NyctFeedHeader, AUTO)


PB_BIND(NyctTripDescriptor, NyctTripDescriptor, AUTO)


PB_BIND(NyctStopTimeUpdate, NyctStopTimeUpdate, AUTO)


/* Definition for extension field nyct_feed_header */
typedef struct _nyct_feed_header_extmsg {
    NyctFeedHeader nyct_feed_header;
} nyct_feed_header_extmsg;
#define nyct_feed_header_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  nyct_feed_header, 1001)
#define nyct_feed_header_extmsg_CALLBACK NULL
#define nyct_feed_header_extmsg_DEFAULT NULL
#define nyct_feed_header_extmsg_nyct_feed_header_MSGTYPE NyctFeedHeader
pb_byte_t nyct_feed_header_extmsg_default[] = {0x00};
PB_BIND(nyct_feed_header_extmsg, nyct_feed_header_extmsg, 2)
const pb_extension_type_t nyct_feed_header = {
    NULL,
    NULL,
    &nyct_feed_header_extmsg_msg
};

/* Definition for extension field nyct_trip_descriptor */
typedef struct _nyct_trip_descriptor_extmsg {
    NyctTripDescriptor nyct_trip_descriptor;
} nyct_trip_descriptor_extmsg;
#define nyct_trip_descriptor_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  nyct_trip_descriptor, 1001)
#define nyct_trip_descriptor_extmsg_CALLBACK NULL
#define nyct_trip_descriptor_extmsg_DEFAULT NULL
#define nyct_trip_descriptor_extmsg_nyct_trip_descriptor_MSGTYPE NyctTripDescriptor
pb_byte_t nyct_trip_descriptor_extmsg_default[] = {0x00};
PB_BIND(nyct_trip_descriptor_extmsg, nyct_trip_descriptor_extmsg, 2)
const pb_extension_type_t nyct_trip_descriptor = {
    NULL,
    NULL,
    &nyct_trip_descriptor_extmsg_msg
};

/* Definition for extension field nyct_stop_time_update */
typedef struct _nyct_stop_time_update_extmsg {
    NyctStopTimeUpdate nyct_stop_time_update;
} nyct_stop_time_update_extmsg;
#define nyct_stop_time_update_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  nyct_stop_time_update, 1001)
#define nyct_stop_time_update_extmsg_CALLBACK NULL
#define nyct_stop_time_update_extmsg_DEFAULT NULL
#define nyct_stop_time_update_extmsg_nyct_stop_time_update_MSGTYPE NyctStopTimeUpdate
pb_byte_t nyct_stop_time_update_extmsg_default[] = {0x00};
PB_BIND(nyct_stop_time_update_extmsg, nyct_stop_time_update_extmsg, 2)
const pb_extension_type_t nyct_stop_time_update = {
    NULL,
    NULL,
    &nyct_stop_time_update_extmsg_msg
};



